# yaml-language-server: $schema=./node_modules/envio/svm.schema.json
name: solana-metaplex-token-metadata
description: Indexes Metaplex Token Metadata creates and updates on Solana mainnet via HyperSync.
ecosystem: svm
chains:
  - id: solana
    start_block: 417920000
    experimental:
      programs:
        - name: TokenMetadata
          program_id: metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s
          instructions:
            - name: CreateMetadataAccountV3
              discriminator: "0x21"
            - name: UpdateMetadataAccountV2
              discriminator: "0x0f"
