// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MockEntities = require("./MockEntities.bs.js");

function insertMock(id) {
  return id;
}

function updateMock(id) {
  return id;
}

var mockNewGravatarContext = {
  gravatar: {
    insert: (function (gravatarInsert) {
        
      }),
    update: (function (gravatarUpdate) {
        
      }),
    delete: (function (_id) {
        console.log("inimplemented delete");
      })
  }
};

var mockUpdateGravatarContext = {
  gravatar: {
    gravatarWithChanges: (function (param) {
        return MockEntities.gravatarEntity1;
      }),
    insert: (function (gravatarInsert) {
        
      }),
    update: (function (gravatarUpdate) {
        
      }),
    delete: (function (_id) {
        console.log("inimplemented delete");
      })
  }
};

exports.insertMock = insertMock;
exports.updateMock = updateMock;
exports.mockNewGravatarContext = mockNewGravatarContext;
exports.mockUpdateGravatarContext = mockUpdateGravatarContext;
/* No side effect */
