// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Sinon = require("../bindings/Sinon.bs.js");
var Sinon$1 = require("sinon");
var MockEntities = require("./MockEntities.bs.js");

var setMock = Sinon$1.stub();

var mockNewGravatarContext = {
  gravatar: {
    set: (function (gravatarSet) {
        Sinon.callStub1(setMock, gravatarSet.id);
      }),
    delete: (function (_id) {
        console.log("inimplemented delete");
      })
  }
};

var mockUpdateGravatarContext = {
  gravatar: {
    gravatarWithChanges: (function (param) {
        return MockEntities.gravatarEntity1;
      }),
    set: (function (gravatarSet) {
        Sinon.callStub1(setMock, gravatarSet.id);
      }),
    delete: (function (_id) {
        console.log("inimplemented delete");
      })
  }
};

exports.setMock = setMock;
exports.mockNewGravatarContext = mockNewGravatarContext;
exports.mockUpdateGravatarContext = mockUpdateGravatarContext;
/* setMock Not a pure module */
