// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

function deleteDictKey(_dict, _key) {
  return (delete _dict[_key]);
}

var databaseDict = {};

function getGravatarDb(id) {
  return Js_dict.get(databaseDict, id);
}

function setGravatarDb(gravatar) {
  databaseDict[gravatar.id] = gravatar;
}

function batchSetGravatar(batch) {
  return Promise.resolve(Belt_Array.forEach(batch, setGravatarDb));
}

function batchDeleteGravatar(batch) {
  return Promise.resolve(Belt_Array.forEach(batch, (function (entity) {
                    deleteDictKey(databaseDict, entity.id);
                  })));
}

function readGravatarEntities(entityReads) {
  return Promise.resolve(Belt_Array.keepMap(entityReads, (function (id) {
                    return Belt_Option.map(Js_dict.get(databaseDict, id), (function (gravatar) {
                                  return gravatar;
                                }));
                  })));
}

exports.deleteDictKey = deleteDictKey;
exports.databaseDict = databaseDict;
exports.getGravatarDb = getGravatarDb;
exports.setGravatarDb = setGravatarDb;
exports.batchSetGravatar = batchSetGravatar;
exports.batchDeleteGravatar = batchDeleteGravatar;
exports.readGravatarEntities = readGravatarEntities;
/* No side effect */
