// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Types = require("generated/src/Types.bs.js");

var gravatarEntity1 = {
  id: "1001",
  owner: "0x123",
  displayName: "gravatar1",
  imageUrl: "https://gravatar1.com",
  updatesCount: 0
};

var gravatarEntity2 = {
  id: "1002",
  owner: "0x678",
  displayName: "gravatar2",
  imageUrl: "https://gravatar2.com",
  updatesCount: 1
};

var mockEventData1 = {
  event_chain_id: 123,
  event_id: "456"
};

var mockEventData2 = {
  event_chain_id: 123,
  event_id: "789"
};

var gravatarSerialized1 = Types.gravatarEntity_encode(gravatarEntity1);

var gravatarSerialized2 = Types.gravatarEntity_encode(gravatarEntity2);

var mockInMemRow1 = {
  dbOp: /* Create */0,
  entity: gravatarSerialized1,
  eventData: mockEventData1
};

var mockInMemRow2 = {
  dbOp: /* Create */0,
  entity: gravatarSerialized2,
  eventData: mockEventData2
};

exports.gravatarEntity1 = gravatarEntity1;
exports.gravatarEntity2 = gravatarEntity2;
exports.mockEventData1 = mockEventData1;
exports.mockEventData2 = mockEventData2;
exports.gravatarSerialized1 = gravatarSerialized1;
exports.gravatarSerialized2 = gravatarSerialized2;
exports.mockInMemRow1 = mockInMemRow1;
exports.mockInMemRow2 = mockInMemRow2;
/* gravatarSerialized1 Not a pure module */
