// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ethers = require("ethers");
var ContextMock = require("./ContextMock.bs.js");

var newGravatar1_id = BigInt(1001);

var newGravatar1_owner = Ethers.ethers.getAddress("0x1230000000000000000000000000000000000000");

var newGravatar1 = {
  id: newGravatar1_id,
  owner: newGravatar1_owner,
  displayName: "gravatar1",
  imageUrl: "https://gravatar1.com"
};

var newGravatar2_id = BigInt(1002);

var newGravatar2_owner = Ethers.ethers.getAddress("0x4560000000000000000000000000000000000000");

var newGravatar2 = {
  id: newGravatar2_id,
  owner: newGravatar2_owner,
  displayName: "gravatar2",
  imageUrl: "https://gravatar2.com"
};

var newGravatar3_id = BigInt(1003);

var newGravatar3_owner = Ethers.ethers.getAddress("0x7890000000000000000000000000000000000000");

var newGravatar3 = {
  id: newGravatar3_id,
  owner: newGravatar3_owner,
  displayName: "gravatar3",
  imageUrl: "https://gravatar3.com"
};

var setGravatar1_id = BigInt(1001);

var setGravatar1_owner = Ethers.ethers.getAddress("0x1230000000000000000000000000000000000000");

var setGravatar1 = {
  id: setGravatar1_id,
  owner: setGravatar1_owner,
  displayName: "update1",
  imageUrl: "https://gravatar1.com"
};

var setGravatar2_id = BigInt(1002);

var setGravatar2_owner = Ethers.ethers.getAddress("0x4560000000000000000000000000000000000000");

var setGravatar2 = {
  id: setGravatar2_id,
  owner: setGravatar2_owner,
  displayName: "update2",
  imageUrl: "https://gravatar2.com"
};

var setGravatar3_id = BigInt(1003);

var setGravatar3_owner = Ethers.ethers.getAddress("0x7890000000000000000000000000000000000000");

var setGravatar3 = {
  id: setGravatar3_id,
  owner: setGravatar3_owner,
  displayName: "update3",
  imageUrl: "https://gravatar3.com"
};

var newGravatarEventLog1_srcAddress = Ethers.ethers.getAddress("0xabc0000000000000000000000000000000000000");

var newGravatarEventLog1 = {
  params: newGravatar1,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: newGravatarEventLog1_srcAddress,
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var newGravatarEventLog2_srcAddress = Ethers.ethers.getAddress("0xabc0000000000000000000000000000000000000");

var newGravatarEventLog2 = {
  params: newGravatar2,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: newGravatarEventLog2_srcAddress,
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var newGravatarEventLog3_srcAddress = Ethers.ethers.getAddress("0xabc0000000000000000000000000000000000000");

var newGravatarEventLog3 = {
  params: newGravatar3,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: newGravatarEventLog3_srcAddress,
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var setGravatarEventLog1_srcAddress = Ethers.ethers.getAddress("0xabc0000000000000000000000000000000000000");

var setGravatarEventLog1 = {
  params: setGravatar1,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: setGravatarEventLog1_srcAddress,
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var setGravatarEventLog2_srcAddress = Ethers.ethers.getAddress("0xabc0000000000000000000000000000000000000");

var setGravatarEventLog2 = {
  params: setGravatar2,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: setGravatarEventLog2_srcAddress,
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var setGravatarEventLog3_srcAddress = Ethers.ethers.getAddress("0xabc0000000000000000000000000000000000000");

var setGravatarEventLog3 = {
  params: setGravatar3,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: setGravatarEventLog3_srcAddress,
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var eventBatch = [
  {
    TAG: /* GravatarContract_NewGravatar */0,
    _0: newGravatarEventLog1
  },
  {
    TAG: /* GravatarContract_NewGravatar */0,
    _0: newGravatarEventLog2
  },
  {
    TAG: /* GravatarContract_NewGravatar */0,
    _0: newGravatarEventLog3
  },
  {
    TAG: /* GravatarContract_UpdatedGravatar */1,
    _0: setGravatarEventLog1
  },
  {
    TAG: /* GravatarContract_UpdatedGravatar */1,
    _0: setGravatarEventLog2
  },
  {
    TAG: /* GravatarContract_UpdatedGravatar */1,
    _0: setGravatarEventLog3
  }
];

var eventBatchWithContext = [
  {
    TAG: /* GravatarContract_NewGravatarWithContext */0,
    _0: newGravatarEventLog1,
    _1: ContextMock.mockNewGravatarContext
  },
  {
    TAG: /* GravatarContract_NewGravatarWithContext */0,
    _0: newGravatarEventLog2,
    _1: ContextMock.mockNewGravatarContext
  },
  {
    TAG: /* GravatarContract_NewGravatarWithContext */0,
    _0: newGravatarEventLog3,
    _1: ContextMock.mockNewGravatarContext
  },
  {
    TAG: /* GravatarContract_UpdatedGravatarWithContext */1,
    _0: setGravatarEventLog1,
    _1: ContextMock.mockUpdateGravatarContext
  },
  {
    TAG: /* GravatarContract_UpdatedGravatarWithContext */1,
    _0: setGravatarEventLog2,
    _1: ContextMock.mockUpdateGravatarContext
  },
  {
    TAG: /* GravatarContract_UpdatedGravatarWithContext */1,
    _0: setGravatarEventLog3,
    _1: ContextMock.mockUpdateGravatarContext
  }
];

exports.newGravatar1 = newGravatar1;
exports.newGravatar2 = newGravatar2;
exports.newGravatar3 = newGravatar3;
exports.setGravatar1 = setGravatar1;
exports.setGravatar2 = setGravatar2;
exports.setGravatar3 = setGravatar3;
exports.newGravatarEventLog1 = newGravatarEventLog1;
exports.newGravatarEventLog2 = newGravatarEventLog2;
exports.newGravatarEventLog3 = newGravatarEventLog3;
exports.setGravatarEventLog1 = setGravatarEventLog1;
exports.setGravatarEventLog2 = setGravatarEventLog2;
exports.setGravatarEventLog3 = setGravatarEventLog3;
exports.eventBatch = eventBatch;
exports.eventBatchWithContext = eventBatchWithContext;
/* newGravatar1 Not a pure module */
