// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var gravatarEntity1 = {
  id: "1001",
  owner: "0x123",
  displayName: "gravatar1",
  imageUrl: "https://gravatar1.com",
  updatesCount: 0
};

var gravatarEntity2 = {
  id: "1002",
  owner: "0x678",
  displayName: "gravatar2",
  imageUrl: "https://gravatar2.com",
  updatesCount: 1
};

exports.gravatarEntity1 = gravatarEntity1;
exports.gravatarEntity2 = gravatarEntity2;
/* No side effect */
