// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function callStub0(callback_stub) {
  return Curry._1(callback_stub, undefined);
}

function callStub1(callback_stub, arg1) {
  return Curry._1(callback_stub, arg1);
}

exports.callStub0 = callStub0;
exports.callStub1 = callStub1;
/* No side effect */
