// This file is generated by HyperIndex codegen. Do not edit manually.
// It wires project-specific types from `.envio/types.d.ts` into the `envio` module.
// If your project's types look out of date, run `pnpm envio codegen` (or `pnpm codegen`).
/// <reference path="./.envio/types.d.ts" />
