# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: Fuel Greeter Indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    contracts:
      - name: Greeter
        address: 0xb9bc445e5696c966dcf7e5d1237bd03c04e3ba6929bdaedfeebc7aae784c3a0b
        abi_file_path: abis/greeter-abi.json
        handler: ./src/EventHandlers.js
        events:
          - name: NewGreeting
          - name: ClearGreeting
# Preload optimisation makes your indexer much faster.
# But be aware that your handlers will run twice,
# so make sure to use Effect API for external calls.
preload_handlers: true
