// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function gravatarNewGravatarEventHandler($$event, context) {
  Curry._1(context.Gravatar.insert, {
        id: $$event.params.id,
        owner: $$event.params.owner,
        displayName: $$event.params.displayName,
        imageUrl: $$event.params.imageUrl
      });
}

function gravatarUpdateGravatarEventHandler($$event, context) {
  Curry._1(context.Gravatar.update, {
        id: $$event.params.id,
        owner: $$event.params.owner,
        displayName: $$event.params.displayName,
        imageUrl: $$event.params.imageUrl
      });
}

exports.gravatarNewGravatarEventHandler = gravatarNewGravatarEventHandler;
exports.gravatarUpdateGravatarEventHandler = gravatarUpdateGravatarEventHandler;
/* No side effect */
