// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict";

var Curry = require("rescript/lib/js/curry.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

function gravatarNewGravatarLoadEntities(_event) {
  return [];
}

function gravatarNewGravatarEventHandler($$event, context) {
  Curry._1(context.Gravatar.insert, {
    id: $$event.params.id,
    owner: $$event.params.owner,
    displayName: $$event.params.displayName,
    imageUrl: $$event.params.imageUrl,
    updatesCount: 1,
  });
}

function gravatarUpdatedGravatarLoadEntities($$event) {
  return [
    /* GravatarRead */ {
      _0: $$event.params.id,
    },
  ];
}

function gravatarUpdatedGravatarEventHandler($$event, context) {
  var updatesCount = Belt_Option.mapWithDefault(
    Curry._1(context.Gravatar.loadedEntities.getById, $$event.params.id),
    1,
    function (gravatar) {
      return (gravatar.updatesCount + 1) | 0;
    }
  );
  Curry._1(context.Gravatar.update, {
    id: $$event.params.id,
    owner: $$event.params.owner,
    displayName: $$event.params.displayName,
    imageUrl: $$event.params.imageUrl,
    updatesCount: updatesCount,
  });
}

exports.gravatarNewGravatarLoadEntities = gravatarNewGravatarLoadEntities;
exports.gravatarNewGravatarEventHandler = gravatarNewGravatarEventHandler;
exports.gravatarUpdatedGravatarLoadEntities =
  gravatarUpdatedGravatarLoadEntities;
exports.gravatarUpdatedGravatarEventHandler =
  gravatarUpdatedGravatarEventHandler;
/* No side effect */
