// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

function gravatarNewGravatarReadEntities(_event) {
  return [];
}

function gravatarNewGravatarEventHandler($$event, context) {
  Curry._1(context.Gravatar.insert, {
        id: $$event.params.id,
        owner: $$event.params.owner,
        displayName: $$event.params.displayName,
        imageUrl: $$event.params.imageUrl,
        updatesCount: 1
      });
}

function gravatarUpdateGravatarReadEntities($$event) {
  return [/* GravatarRead */{
            _0: $$event.params.id
          }];
}

function gravatarUpdateGravatarEventHandler($$event, context) {
  var updatesCount = Belt_Option.mapWithDefault(Belt_Array.get(context.Gravatar.readEntities, 0), 1, (function (gravatar) {
          return gravatar.updatesCount + 1 | 0;
        }));
  Curry._1(context.Gravatar.update, {
        id: $$event.params.id,
        owner: $$event.params.owner,
        displayName: $$event.params.displayName,
        imageUrl: $$event.params.imageUrl,
        updatesCount: updatesCount
      });
}

exports.gravatarNewGravatarReadEntities = gravatarNewGravatarReadEntities;
exports.gravatarNewGravatarEventHandler = gravatarNewGravatarEventHandler;
exports.gravatarUpdateGravatarReadEntities = gravatarUpdateGravatarReadEntities;
exports.gravatarUpdateGravatarEventHandler = gravatarUpdateGravatarEventHandler;
/* No side effect */
