// A getWhere is answered from the in-memory indexes, which are kept up to date
// across every set and delete, and from the rows earlier queries loaded. Any
// slip in that bookkeeping shows as a result that differs from filtering the
// entities directly, so a seeded run of random writes and queries is checked
// against exactly that.
let _ = InternalTestIndexer.fromUserApi(
  ~configYaml=`
name: get-where-fuzz
chains:
  - id: 1
    start_block: 1
    contracts:
      - name: Gravatar
        address: "0x2B2f78c5BF6D9C12Ee1225D5F374aa91204580c3"
        events:
          - event: "FactoryEvent(address indexed contract, string testCase)"
`,
  ~schema=`
type Item {
  id: ID!
  owner: String! @index
  rank: Int! @index
  tags: [String!]!
}

type Probe {
  id: ID!
}
`,
  ~handlers=`
import { indexer, type Item } from "envio";

const makeRandom = (seed: number) => {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
};
type Random = () => number;
const pick = <T,>(random: Random, items: readonly T[]) => items[Math.floor(random() * items.length)] as T;

const owners = ["a", "b", "c", "d"];
const ranks = [0, 1, 2, 3, 4];
const tagPool: readonly (readonly string[])[] = [[], ["x"], ["x", "y"], ["y"], ["x", "x"]];
const makeItem = (random: Random, id: string): Item => ({
  id,
  owner: pick(random, owners),
  rank: pick(random, ranks),
  tags: pick(random, tagPool),
});
// The rows the store starts with, regenerated by both events from one seed.
const seedItems = () => {
  const random = makeRandom(7);
  const items = new Map<string, Item>();
  for (let i = 0; i < 40; i++) {
    const item = makeItem(random, \`i\${i}\`);
    items.set(item.id, item);
  }
  return items;
};

type Filter = Record<string, Record<string, unknown>>;
const operators = ["_eq", "_gt", "_lt", "_gte", "_lte", "_in"] as const;
const fields = ["owner", "rank", "tags"] as const;
const poolOf = (field: (typeof fields)[number]): readonly unknown[] =>
  field === "owner" ? owners : field === "rank" ? ranks : tagPool;
const makeFilter = (random: Random): Filter => {
  const filter: Record<string, Record<string, unknown>> = {};
  const fieldsCount = random() < 0.3 ? 2 : 1;
  while (Object.keys(filter).length < fieldsCount) {
    const field = pick(random, fields);
    const ops: Record<string, unknown> = {};
    const opsCount = random() < 0.25 ? 2 : 1;
    while (Object.keys(ops).length < opsCount) {
      const op = pick(random, operators);
      ops[op] =
        op === "_in"
          ? Array.from({ length: Math.floor(random() * 4) }, () => pick(random, poolOf(field)))
          : pick(random, poolOf(field));
    }
    filter[field] = ops;
  }
  return filter;
};

// The oracle: the operators applied directly, with lists ordered
// lexicographically the way Postgres orders them.
const compare = (a: unknown, b: unknown): number => {
  if (Array.isArray(a) && Array.isArray(b)) {
    const n = Math.min(a.length, b.length);
    for (let i = 0; i < n; i++) {
      const c = compare(a[i], b[i]);
      if (c !== 0) return c;
    }
    return a.length - b.length;
  }
  return (a as number) < (b as number) ? -1 : (a as number) > (b as number) ? 1 : 0;
};
const matches = (item: Item, filter: Filter) =>
  Object.entries(filter).every(([field, ops]) =>
    Object.entries(ops).every(([op, value]) => {
      const c = compare(item[field as keyof Item], value);
      switch (op) {
        case "_eq": return c === 0;
        case "_gt": return c > 0;
        case "_lt": return c < 0;
        case "_gte": return c >= 0;
        case "_lte": return c <= 0;
        default: return (value as unknown[]).some((candidate) => compare(item[field as keyof Item], candidate) === 0);
      }
    }),
  );

const sortedIds = (items: Iterable<Item>) => [...items].map((i) => i.id).sort().join(",");

indexer.onEvent({ contract: "Gravatar", event: "FactoryEvent" }, async ({ event, context }) => {
  if (context.isPreload) {
    return;
  }
  if (event.params.testCase === "seed") {
    for (const item of seedItems().values()) {
      context.Item.set(item);
    }
    return;
  }

  const oracle = seedItems();
  const random = makeRandom(11);
  const mismatches: string[] = [];
  const getWhere = (filter: Filter) =>
    context.Item.getWhere(filter as unknown as Parameters<typeof context.Item.getWhere>[0]);
  const check = (filter: Filter, actual: Item[]) => {
    const expected = sortedIds([...oracle.values()].filter((item) => matches(item, filter)));
    const got = sortedIds(actual);
    if (expected !== got) {
      mismatches.push(\`\${JSON.stringify(filter)} expected [\${expected}] got [\${got}]\`);
    }
  };

  for (let step = 0; step < 400; step++) {
    const roll = random();
    if (roll < 0.3) {
      const item = makeItem(random, \`i\${Math.floor(random() * 60)}\`);
      context.Item.set(item);
      oracle.set(item.id, item);
    } else if (roll < 0.4) {
      const id = \`i\${Math.floor(random() * 60)}\`;
      context.Item.deleteUnsafe(id);
      oracle.delete(id);
    } else if (roll < 0.7) {
      const filter = makeFilter(random);
      check(filter, await getWhere(filter));
    } else {
      // Concurrent calls batch into one load, and may merge into one query.
      const filters = Array.from({ length: 2 + Math.floor(random() * 3) }, () => makeFilter(random));
      const results = await Promise.all(filters.map(getWhere));
      filters.forEach((filter, index) => check(filter, results[index] as Item[]));
    }
  }

  context.Probe.set({ id: mismatches.length === 0 ? "ok" : mismatches.slice(0, 5).join(" | ") });
});
`,
  ~test=`
import { describe, it } from "vitest";
import { createTestIndexer } from "envio";

describe("getWhere under random writes", () => {
  it("answers every filter the way a direct scan of the entities does", async (t) => {
    const indexer = createTestIndexer();
    const contract = "0x1234567890123456789012345678901234567890";

    // Seeded in a run of its own, so the second run has to load them.
    await indexer.process({
      chains: {
        1: {
          startBlock: 1,
          endBlock: 100,
          simulate: [
            { contract: "Gravatar", event: "FactoryEvent", params: { contract, testCase: "seed" } },
          ],
        },
      },
    });
    const result = await indexer.process({
      chains: {
        1: {
          startBlock: 101,
          endBlock: 200,
          simulate: [
            { contract: "Gravatar", event: "FactoryEvent", params: { contract, testCase: "ops" } },
          ],
        },
      },
    });

    t.expect(result.changes[0]?.Probe).toEqual({ sets: [{ id: "ok" }] });
  });
});
`,
)
