open Vitest

// https://github.com/enviodev/hyperindex/issues/794 — `envio init` on
// 0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2 (eth mainnet) names the contract
// after the verified source, `InitializableImmutableAdminUpgradeabilityProxy`,
// and writes one `{Contract}_{Event}` entity per event. Nothing caps that
// concatenation, so the generated schema carries entity names past the 63-char
// Postgres identifier limit and the project it just scaffolded won't parse.
let contractName = "InitializableImmutableAdminUpgradeabilityProxy"

let configYaml = `
name: aave-pool
chains:
  - id: 1
    start_block: 0
    contracts:
      - name: ${contractName}
        address: "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2"
        events:
          - event: MintedToTreasury(address indexed reserve, uint256 amountMinted)
          - event: ReserveUsedAsCollateralDisabled(address indexed reserve, address indexed user)
`

let entityFor = eventName => `${contractName}_${eventName}`

let schemaFor = eventName => `
type ${entityFor(eventName)} {
  id: ID!
  reserve: String!
}
`

let parseError = eventName =>
  InternalTestIndexer.parseError(~schema=schemaFor(eventName), ~configYaml)

describe("Entity names generated by envio init", () => {
  // 63 chars exactly — the longest event name on this ABI that still fits.
  it("accepts a generated name that fits the Postgres limit", t => {
    t.expect(
      InternalTestIndexer.fromUserApi(
        ~schema=schemaFor("MintedToTreasury"),
        ~configYaml,
      ).config.userEntities->Array.map(e => e.name),
    ).toEqual(["InitializableImmutableAdminUpgradeabilityProxy_MintedToTreasury"])
  })

  // The bug: this is the schema `envio init` writes, and it doesn't parse.
  it("rejects the schema envio init writes for a longer event name", t => {
    t.expect(parseError("ReserveUsedAsCollateralDisabled")).toBe(
      "schema.graphql:2:1: Entity name 'InitializableImmutableAdminUpgradeabilityProxy_ReserveUsedAsCollateralDisabled' is too long. It must be less than 64 characters.",
    )
  })
})
