// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Ethers = require("generated/src/bindings/Ethers.bs.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

function gravatarNewGravatarLoadEntities(_event) {
  return [];
}

function gravatarNewGravatarEventHandler($$event, context) {
  Curry._1(context.gravatar.insert, {
        id: $$event.params.id.toString(),
        owner: Ethers.ethAddressToString($$event.params.owner),
        displayName: $$event.params.displayName,
        imageUrl: $$event.params.imageUrl,
        updatesCount: 1
      });
}

function gravatarUpdatedGravatarLoadEntities($$event, contextUpdator) {
  Curry._1(contextUpdator.gravatar.gravatarWithChangesLoad, $$event.params.id.toString());
}

function gravatarUpdatedGravatarEventHandler($$event, context) {
  var updatesCount = Belt_Option.mapWithDefault(Curry._1(context.gravatar.gravatarWithChanges, undefined), 1, (function (gravatar) {
          return gravatar.updatesCount + 1 | 0;
        }));
  Curry._1(context.gravatar.update, {
        id: $$event.params.id.toString(),
        owner: Ethers.ethAddressToString($$event.params.owner),
        displayName: $$event.params.displayName,
        imageUrl: $$event.params.imageUrl,
        updatesCount: updatesCount
      });
}

exports.gravatarNewGravatarLoadEntities = gravatarNewGravatarLoadEntities;
exports.gravatarNewGravatarEventHandler = gravatarNewGravatarEventHandler;
exports.gravatarUpdatedGravatarLoadEntities = gravatarUpdatedGravatarLoadEntities;
exports.gravatarUpdatedGravatarEventHandler = gravatarUpdatedGravatarEventHandler;
/* Ethers Not a pure module */
