# yaml-language-server: $schema=../../../codegenerator/cli/npm/envio/evm.schema.json
name: Ploffen
description: Gravatar for Ethereum
networks:
  - id: 1337
    rpc_config:
      url: http://localhost:8545
    start_block: 0
    contracts:
      - name: Ploffen
        abi_file_path: ../contracts/abis/Ploffen.json
        address: "0xa2F6E6029638cCb484A2ccb6414499aD3e825CaC"
        handler: ./src/EventHandlers.bs.js
        events:
          - event: "CreatePloffen"
            requiredEntities: []
          - event: "StartPloffen"
            requiredEntities: # if this field isn't specified it should default to include all entities
              - name: "Ploffengame"
                labels:
                  - "unstartedPloffen"
          - event: "PlayPloffen"
            requiredEntities:
              - name: "Ploffengame"
                labels:
                  - "startedPloffen"
              - name: "User"
                labels:
                  - "user"
          - event: "WinPloffen"
            requiredEntities:
              - name: "Ploffengame"
                labels:
                  - "startedPloffen"
              - name: "User"
                labels:
                  - "user"
