// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var TaskLiveGravatarTxsJs = require("./taskLiveGravatarTxs.js").default;

function liveGravatarTxs(prim) {
  return TaskLiveGravatarTxsJs();
}

exports.liveGravatarTxs = liveGravatarTxs;
/* ./taskLiveGravatarTxs.js Not a pure module */
