// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SetupNodeAndContractsJs = require("./setupNodeAndContracts.js").default;

function setupNodeAndContracts(prim) {
  return SetupNodeAndContractsJs();
}

exports.setupNodeAndContracts = setupNodeAndContracts;
/* ./setupNodeAndContracts.js Not a pure module */
