// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function getContext(param) {
  
}

var NewGravatarEvent = {
  getContext: getContext
};

var GravatarContract = {
  NewGravatarEvent: NewGravatarEvent
};

exports.GravatarContract = GravatarContract;
/* No side effect */
