// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function entitySerialize(entity) {
  return "gravatar" + entity._0 + "";
}

var NewGravatarTypes = {};

var UpdatedGravatarTypes = {};

var GravatarContract = {
  NewGravatarTypes: NewGravatarTypes,
  UpdatedGravatarTypes: UpdatedGravatarTypes
};

function eventNameToString(eventName) {
  if (eventName) {
    return "UpdatedGravatar";
  } else {
    return "NewGravatar";
  }
}

exports.entitySerialize = entitySerialize;
exports.GravatarContract = GravatarContract;
exports.eventNameToString = eventNameToString;
/* No side effect */
