// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");

Jest.describe("E2E Mock Event Batch", (function (param) {
        Jest.test("Dummy Test to be replaced with E2E", (function (param) {
                return Jest.pass;
              }));
      }));

/*  Not a pure module */
