// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SetupNodeAndContractsJs = require("./setupNodeAndContracts.js");
var SetupNodeAndContractsJs$1 = require("./setupNodeAndContracts.js").default;

function setupNodeAndContracts(prim) {
  return SetupNodeAndContractsJs$1(prim);
}

function deployContract(prim) {
  return SetupNodeAndContractsJs.deployContract();
}

exports.setupNodeAndContracts = setupNodeAndContracts;
exports.deployContract = deployContract;
/* ./setupNodeAndContracts.js Not a pure module */
