// This file wires project-specific types generated by `envio codegen` into the `envio`
// package. Keep it at the project root so TypeScript picks it up via the augmentation
// contract. Regenerated on every codegen run; do not edit.
/// <reference path="./.envio/types.d.ts" />
