// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var MockEntities = require("./MockEntities.bs.js");

var insertMock = jest.fn(function (id) {
      return id;
    });

var getByIdMock = jest.fn(function (id) {
      return id;
    });

var updateMock = jest.fn(function (id) {
      return id;
    });

function loadedEntitiesMock_getById(id) {
  Curry._1(getByIdMock, id);
}

function loadedEntitiesMock_getAllLoaded(param) {
  return [MockEntities.gravatarEntity1];
}

var loadedEntitiesMock = {
  getById: loadedEntitiesMock_getById,
  getAllLoaded: loadedEntitiesMock_getAllLoaded
};

var mockContext = {
  Gravatar: {
    insert: (function (gravatarInsert) {
        Curry._1(insertMock, gravatarInsert.id);
      }),
    update: (function (gravatarUpdate) {
        Curry._1(updateMock, gravatarUpdate.id);
      }),
    loadedEntities: loadedEntitiesMock
  }
};

exports.insertMock = insertMock;
exports.getByIdMock = getByIdMock;
exports.updateMock = updateMock;
exports.loadedEntitiesMock = loadedEntitiesMock;
exports.mockContext = mockContext;
/* insertMock Not a pure module */
