// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var MockEntities = require("./MockEntities.bs.js");

var insertMock = jest.fn(function (id) {
      return id;
    });

var updateMock = jest.fn(function (id) {
      return id;
    });

var mockNewGravatarContext = {
  gravatar: {
    insert: (function (gravatarInsert) {
        Curry._1(insertMock, gravatarInsert.id);
      }),
    update: (function (gravatarUpdate) {
        Curry._1(updateMock, gravatarUpdate.id);
      }),
    delete: (function (_id) {
        console.log("inimplemented delete");
      })
  }
};

var mockUpdateGravatarContext = {
  gravatar: {
    gravatarWithChanges: (function (param) {
        return MockEntities.gravatarEntity1;
      }),
    insert: (function (gravatarInsert) {
        Curry._1(insertMock, gravatarInsert.id);
      }),
    update: (function (gravatarUpdate) {
        Curry._1(updateMock, gravatarUpdate.id);
      }),
    delete: (function (_id) {
        console.log("inimplemented delete");
      })
  }
};

exports.insertMock = insertMock;
exports.updateMock = updateMock;
exports.mockNewGravatarContext = mockNewGravatarContext;
exports.mockUpdateGravatarContext = mockUpdateGravatarContext;
/* insertMock Not a pure module */
