// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ethers = require("ethers");

var newGravatar1_id = BigInt(1001);

var newGravatar1_owner = Ethers.ethers.getAddress("0x1230000000000000000000000000000000000000");

var newGravatar1 = {
  id: newGravatar1_id,
  owner: newGravatar1_owner,
  displayName: "gravatar1",
  imageUrl: "https://gravatar1.com"
};

var newGravatar2_id = BigInt(1002);

var newGravatar2_owner = Ethers.ethers.getAddress("0x4560000000000000000000000000000000000000");

var newGravatar2 = {
  id: newGravatar2_id,
  owner: newGravatar2_owner,
  displayName: "gravatar2",
  imageUrl: "https://gravatar2.com"
};

var newGravatar3_id = BigInt(1003);

var newGravatar3_owner = Ethers.ethers.getAddress("0x7890000000000000000000000000000000000000");

var newGravatar3 = {
  id: newGravatar3_id,
  owner: newGravatar3_owner,
  displayName: "gravatar3",
  imageUrl: "https://gravatar3.com"
};

var updatedGravatar1_id = BigInt(1001);

var updatedGravatar1_owner = Ethers.ethers.getAddress("0x1230000000000000000000000000000000000000");

var updatedGravatar1 = {
  id: updatedGravatar1_id,
  owner: updatedGravatar1_owner,
  displayName: "update1",
  imageUrl: "https://gravatar1.com"
};

var updatedGravatar2_id = BigInt(1002);

var updatedGravatar2_owner = Ethers.ethers.getAddress("0x4560000000000000000000000000000000000000");

var updatedGravatar2 = {
  id: updatedGravatar2_id,
  owner: updatedGravatar2_owner,
  displayName: "update2",
  imageUrl: "https://gravatar2.com"
};

var updatedGravatar3_id = BigInt(1003);

var updatedGravatar3_owner = Ethers.ethers.getAddress("0x7890000000000000000000000000000000000000");

var updatedGravatar3 = {
  id: updatedGravatar3_id,
  owner: updatedGravatar3_owner,
  displayName: "update3",
  imageUrl: "https://gravatar3.com"
};

var newGravatarEventLog1 = {
  params: newGravatar1,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var newGravatarEventLog2 = {
  params: newGravatar2,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var newGravatarEventLog3 = {
  params: newGravatar3,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var updatedGravatarEventLog1 = {
  params: updatedGravatar1,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var updatedGravatarEventLog2 = {
  params: updatedGravatar2,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var updatedGravatarEventLog3 = {
  params: updatedGravatar3,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var eventBatch = [
  {
    TAG: /* GravatarContract_NewGravatar */0,
    _0: newGravatarEventLog1
  },
  {
    TAG: /* GravatarContract_NewGravatar */0,
    _0: newGravatarEventLog2
  },
  {
    TAG: /* GravatarContract_NewGravatar */0,
    _0: newGravatarEventLog3
  },
  {
    TAG: /* GravatarContract_UpdatedGravatar */1,
    _0: updatedGravatarEventLog1
  },
  {
    TAG: /* GravatarContract_UpdatedGravatar */1,
    _0: updatedGravatarEventLog2
  },
  {
    TAG: /* GravatarContract_UpdatedGravatar */1,
    _0: updatedGravatarEventLog3
  }
];

exports.newGravatar1 = newGravatar1;
exports.newGravatar2 = newGravatar2;
exports.newGravatar3 = newGravatar3;
exports.updatedGravatar1 = updatedGravatar1;
exports.updatedGravatar2 = updatedGravatar2;
exports.updatedGravatar3 = updatedGravatar3;
exports.newGravatarEventLog1 = newGravatarEventLog1;
exports.newGravatarEventLog2 = newGravatarEventLog2;
exports.newGravatarEventLog3 = newGravatarEventLog3;
exports.updatedGravatarEventLog1 = updatedGravatarEventLog1;
exports.updatedGravatarEventLog2 = updatedGravatarEventLog2;
exports.updatedGravatarEventLog3 = updatedGravatarEventLog3;
exports.eventBatch = eventBatch;
/* newGravatar1 Not a pure module */
