// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var newGravatar1 = {
  id: "1001",
  owner: "0x123",
  displayName: "gravatar1",
  imageUrl: "https://gravatar1.com"
};

var newGravatar2 = {
  id: "1002",
  owner: "0x456",
  displayName: "gravatar2",
  imageUrl: "https://gravatar2.com"
};

var newGravatar3 = {
  id: "1003",
  owner: "0x789",
  displayName: "gravatar3",
  imageUrl: "https://gravatar3.com"
};

var updatedGravatar1 = {
  id: "1001",
  owner: "0x123",
  displayName: "update1",
  imageUrl: "https://gravatar1.com"
};

var updatedGravatar2 = {
  id: "1002",
  owner: "0x456",
  displayName: "update2",
  imageUrl: "https://gravatar2.com"
};

var updatedGravatar3 = {
  id: "1003",
  owner: "0x789",
  displayName: "update3",
  imageUrl: "https://gravatar3.com"
};

var newGravatarEventLog1 = {
  params: newGravatar1,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var newGravatarEventLog2 = {
  params: newGravatar2,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var newGravatarEventLog3 = {
  params: newGravatar3,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var updatedGravatarEventLog1 = {
  params: updatedGravatar1,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var updatedGravatarEventLog2 = {
  params: updatedGravatar2,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var updatedGravatarEventLog3 = {
  params: updatedGravatar3,
  blockNumber: 1,
  blockTimestamp: 1,
  blockHash: "deasne",
  srcAddress: "0xabc",
  transactionHash: "0xaaa",
  transactionIndex: 1,
  logIndex: 1
};

var eventBatch = [
  {
    TAG: /* NewGravatar */0,
    _0: newGravatarEventLog1
  },
  {
    TAG: /* NewGravatar */0,
    _0: newGravatarEventLog2
  },
  {
    TAG: /* NewGravatar */0,
    _0: newGravatarEventLog3
  },
  {
    TAG: /* UpdatedGravatar */1,
    _0: updatedGravatarEventLog1
  },
  {
    TAG: /* UpdatedGravatar */1,
    _0: updatedGravatarEventLog2
  },
  {
    TAG: /* UpdatedGravatar */1,
    _0: updatedGravatarEventLog3
  }
];

exports.newGravatar1 = newGravatar1;
exports.newGravatar2 = newGravatar2;
exports.newGravatar3 = newGravatar3;
exports.updatedGravatar1 = updatedGravatar1;
exports.updatedGravatar2 = updatedGravatar2;
exports.updatedGravatar3 = updatedGravatar3;
exports.newGravatarEventLog1 = newGravatarEventLog1;
exports.newGravatarEventLog2 = newGravatarEventLog2;
exports.newGravatarEventLog3 = newGravatarEventLog3;
exports.updatedGravatarEventLog1 = updatedGravatarEventLog1;
exports.updatedGravatarEventLog2 = updatedGravatarEventLog2;
exports.updatedGravatarEventLog3 = updatedGravatarEventLog3;
exports.eventBatch = eventBatch;
/* No side effect */
